name: Python CI

on: [push, pull_request]

jobs:
  lint-and-test:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        poetry-version: ["latest", "main", "1.8.3"]
        os: [ubuntu-24.04, ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Run pylint
        run: |
          poetry run pylint *.py

      - name: Run flake8
        run: |
          poetry run flake8 *.py

      - name: Run black check
        run: |
          poetry run black --check *.py

      - name: Run pydocstyle
        run: |
          poetry run pydocstyle *.py

      - name: Run pytest
        run: |
          poetry run pytest

